"use strict";

const
    mongoose = require("mongoose"),
    Schema = mongoose.Schema;

let OrderSchema = new Schema({
    AdditionName: null,
    AdditionPrice: null,
    AddressId: null,
    AddressTail: null,
    City: null,
    ClientAccountPaymentValue: null,
    ClientOrderStateId: null,
    Comment: null,
    CommentRequired: null,
    Country: null,
    DateOrder: null,
    DeliveryChoice: null,
    DeliveryPrice: null,
    DeliveryVariant: null,
    DeliveryVariantId: null,
    DeliveryVariantTypeId: null,
    District: null,
    DueDeliveryDate: null,
    FirstName: null,
    FlexMaxDateTime: null,
    FlexMinDateTime: null,
    IsOrderCancel: null,
    LastName: null,
    MaxSpasibo: null,
    MiddleName: null,
    OrderSumm: null,
    PayOrderSumm: null,
    PaymentType: null,
    PaymentTypeId: null,
    Phone: null,
    PhoneRequired: null,
    Region: null,
    ScoreToAdd: null,
    ShowRepeatOrder: null,
    State: null,
    ZipCode: null,
    Postings: [
        {
            ClientAccountPayment: null,
            ClientDeliveryPrice: null,
            ClientOrderId: null,
            ClientOrderStateId: null,
            CourierNum: null,
            CourierPostingStoreDate: null,
            ExtCode: null,
            FullNum: null,
            FullSumm: null,
            Id: null,
            IsPrepay: null,
            ItemSumm: null,
            NeedConfirmReceived: null,
            PaymentTypeId: null,
            PostingDate: null,
        },
    ],
    OrderPosting: [
        {}
    ],
    StateChangeMoment: null,
    PostingItem: [],
    Items: [
        {
            ItemId: null,
            ItemType: null,
            ItemTypeId: null,
            Name: null,
            Qty: null,
            Annotation: null,
            Author: null,
            CanceledQty: null,
            ClientOrderId: null,
            ComingDate: null,
            HasScoresDiscount: null,
            Path: null,
            PreRelease: null,
            Price: null,
            ProcessQty: null,
            ResQty: null,
            ScoresAdded: null,
            ScoresDiscountAmountNeeded: null,
            ScoresDiscountPrice: null,
            Url: null,
        }
    ],
});

module.exports = mongoose.model("order", OrderSchema);